package exceptionPractices;

import java.util.InputMismatchException;
import java.util.Scanner;

public class MultipleCatchBlock {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try {
		Scanner sc = new Scanner(System.in);
		System.out.println("enter the first number");
		int num1 = sc.nextInt();
		System.out.println("enter the second number");
		int num2 = sc.nextInt();
		int result = num1 /num2;
		System.out.println("The division of the number is" +result);
		}
		catch(ArithmeticException e) {
			System.out.println("Do not enter the zero in the denominator");
		
		}
		catch(InputMismatchException e) {
			System.out.println("Please enter only integer value");
		}
		catch(Exception e) {
			System.out.println("Please enter valid input");
			
		}
		

	}

}
